version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: on-failure
    container_name: querying-sample_db
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Your_password123
    ports:
      - 20342:1433
    volumes:
      - querying-sample:/var/opt/mssql

volumes:
  querying-sample: